/*
 * 定义类型常量
*/
const SHOW_ALERT = 'SHOW_ALERT'
const ALERT_MSG = 'ALERT_MSG'
const ALERTCALLBACK = 'ALERTCALLBACK'
const PAGEINDEX = 'PAGEINDEX'
const EDITPWDSHOW = 'EDITPWDSHOW'

export default {
	SHOW_ALERT,
	ALERT_MSG,
	ALERTCALLBACK,
	PAGEINDEX,
	EDITPWDSHOW
}