/*
 * 定义类型常量
*/
const SHOWALERT = 'SHOW_ALERT'
const ALERTMSG = 'ALERT_MSG'
const ALERTCALLBACK = 'ALERTCALLBACK'
const PAGEINDEX = 'PAGEINDEX'
const EDITPWDSHOW = 'EDITPWDSHOW'

export default {
	SHOWALERT,
	ALERTMSG,
	ALERTCALLBACK,
	PAGEINDEX,
	EDITPWDSHOW
}